version: '3.8'

services:
  mongo:
    image: mongo:6.0.13
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7.2
    ports:
      - '6379:6379'
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - MONGO_URI=mongodb://mongo:27017/novasphere
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped

volumes:
  mongo-data:
